/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FileMetadata {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'size' : bigint,
  'folderId' : [] | [string],
  'uploadedAt' : bigint,
}
export interface FolderMetadata {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'tags' : Array<string>,
  'description' : string,
  'updatedAt' : bigint,
  'collaborators' : Array<Principal>,
  'parentFolderId' : [] | [string],
  'isPublic' : boolean,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFolder' : ActorMethod<
    [
      string,
      [] | [string],
      boolean,
      Array<Principal>,
      string,
      Array<string>,
      string,
    ],
    string
  >,
  'deleteFolder' : ActorMethod<[string, boolean, boolean], boolean>,
  'downloadFileChunk' : ActorMethod<[string, bigint], [] | [Uint8Array]>,
  'editFolder' : ActorMethod<
    [string, boolean, Array<Principal>, string, Array<string>, string],
    boolean
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileMetadata' : ActorMethod<[string], [] | [FileMetadata]>,
  'getFolderMetadata' : ActorMethod<[string], [] | [FolderMetadata]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFiles' : ActorMethod<[], Array<FileMetadata>>,
  'listFilesByFolder' : ActorMethod<[[] | [string]], Array<FileMetadata>>,
  'listFolders' : ActorMethod<[], Array<FolderMetadata>>,
  'moveFolder' : ActorMethod<[string, [] | [string]], boolean>,
  'renameFolder' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadFileChunk' : ActorMethod<
    [string, string, bigint, Uint8Array, bigint, bigint, [] | [string]],
    [] | [string]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];