/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface FileMetadata {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'size' : bigint,
  'folderId' : [] | [string],
  'uploadedAt' : bigint,
}
export interface Folder {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'parentId' : [] | [string],
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFolder' : ActorMethod<[string, [] | [string]], string>,
  'deleteExpiredTrash' : ActorMethod<[], bigint>,
  'favoriteFolder' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavoriteFolders' : ActorMethod<[], Array<Folder>>,
  'getFilesInFolder' : ActorMethod<[string], Array<FileMetadata>>,
  'getFilesInFolderWithFavorites' : ActorMethod<[string], Array<FileMetadata>>,
  'getFolder' : ActorMethod<[string], [] | [Folder]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isFavoriteFolder' : ActorMethod<[string], boolean>,
  'listAllFoldersWithFavorites' : ActorMethod<[], Array<Folder>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFolders' : ActorMethod<[], Array<Folder>>,
  'moveFilesToFolder' : ActorMethod<[Array<string>, string], boolean>,
  /**
   * / Improved function to move a folder (with recursive subtree traversal and proper authorization)
   */
  'moveFolder' : ActorMethod<[string, [] | [string]], boolean>,
  'permanentlyDeleteFolder' : ActorMethod<[string], boolean>,
  'renameFolder' : ActorMethod<[string, string], boolean>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unfavoriteFolder' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];